AWSTemplateFormatVersion: '2010-09-09'

Description: 'ASG Template: Auto Scaling Group & Launch Configuration'

Mappings:

  # AcctMap - use this if you wish to easily deploy this stack in
  # multiple accounts. e.g. PRODUCTION & DEVELOPMENT
  # If using with one account only, specify and reference only one
  # account, the other will be ignored.
  AcctMap:
    "876543210987" : # customize to your account
      "AcctName" : "DEVELOPMENT"
    "123456789012" : # customize to your account
      "AcctName" : "PRODUCTION"

  # AMIMap - use this to map AMIs in multiple regions and accounts
  # Only the region is required for public AMIs. Useful if you have
  # unshared private AMIs in multiple accounts & regions.
  AMIMap:
    us-west-2:
      "DEVELOPMENT" : "ami-e689729e"
      "PRODUCTION" : "ami-e689729e"
    us-east-1:
      "DEVELOPMENT" : "ami-c5062ba0"
      "PRODUCTION" : "ami-c5062ba0"

  KeypairMap:
    us-west-2:
      "DEVELOPMENT" : "oregon-dev"
      "PRODUCTION" : "oregon-prod"
    us-east-1:
      "DEVELOPMENT" : "virginia-dev"
      "PRODUCTION" : "virginia-prod"

  InstanceSizeMap:
    t2:
      "micro" : "t2.micro"
      "small" : "t2.small"
      "medium" : "t2.medium"
      "large" : "t2.large"
    m4:
      "small" : "m4.large"
      "medium" : "m4.xlarge"
      "large" : "m4.4xlarge"

  ProfileMap:
    ec2-profile:
      "DEVELOPMENT" : "DevEC2Profile"
      "PRODUCTION"  : "ProdEC2Profile"

Parameters:
  VPCStackName:
    Description: Name of the VPC stack we're referencing
    Type: String
    Default: demo-vpc

  NLBStackName:
    Description: Name of the NLB stack we're referencing
    Type: String
    Default: demo-nlb

  Monitoring:
    Description: Toggle detailed instance monitoring for instances in the ASG.  Set to True for detailed monitoring. Additional fees will apply.
    Type: String
    MinLength: '1'
    MaxLength: '128'
    Default: false

  InstanceType:
    Description: Specifies the instance type of the EC2 instances that will be deployed into the ASG.
    Type: String
    AllowedValues: 
      - t2.micro
      - t2.medium
      - t2.large
      - m4.large
    Default: t2.micro

  DesiredInstanceAmount:
    Description: Desired number of instances in the ASG.
    Type: Number
    Default: 3

  HealthChkGracePeriod:
    Description: The length of time in seconds after a new EC2 instance comes into service that Auto Scaling starts checking its health.
    Type: Number
    Default: 300

  ASGMaxSize:
    Description: Maximum number of instances to be deployed into the ASG.
    Type: Number
    Default: 6

  ASGMinSize:
    Description: Minimum number of instances to be deployed into the ASG.
    Type: Number
    Default: 2

  ASGCooldown:
    Description: The number of seconds after a scaling activity is completed before any further scaling activities can start.
    Type: Number
    Default: 300

  ASGTerminationPolicies:
    Description: Used to specify the rules that dictate which instances are terminated during scale-in events.
    Type: String
    MinLength: '1'
    MaxLength: '128'
    Default: Default

  UpdatePolicyMaxBatchSize:
    Description: Specifies the maximum number of instances that AWS CloudFormation updates at a time.
    Type: Number
    Default: 1

  UpdatePolicyMinInstancesInService:
    Description: Minimum number of instances in service while other instances are being updated.
    Type: Number
    Default: 2

  AvailabilityZone:
    Description: Choose one AZ as the Network Loan Balancer needs exactly ONE IP address
    Type: String
    Default: AZ1
    AllowedValues:
      - AZ1
      - AZ2
      - AZ3

  PublicIP:
    Description: Set to True if you wish the instances in the ASG to have a public IP.
    Type: String
    Default: true
    AllowedValues: 
      - true
      - false

  NginxConfigBucket:
    Type: String
    Default: YourBucketName/Prefix

# "${AWS::StackName}-ConfigBucket"

Resources:
#########################################################################
# Auto Scaling Group Launch Configuration

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: !Ref PublicIP
      ImageId: !FindInMap [AMIMap, !Ref "AWS::Region", !FindInMap [AcctMap, !Ref "AWS::AccountId", AcctName ] ]
      InstanceMonitoring: !Ref Monitoring
      InstanceType: !Ref InstanceType
      KeyName: !FindInMap [KeypairMap, !Ref "AWS::Region", !FindInMap [AcctMap, !Ref "AWS::AccountId", AcctName ] ]
      IamInstanceProfile: !FindInMap [ProfileMap, ec2-profile, !FindInMap [AcctMap, !Ref "AWS::AccountId", AcctName ] ]
      SecurityGroups:
        - Fn::ImportValue: !Sub "${VPCStackName}-SGEC2"
        - Fn::ImportValue: !Sub "${VPCStackName}-SGSSH"
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            yum update -y
            yum install -y nginx
            chkconfig nginx on

            aws s3 cp s3://${NginxConfigBucket}/nginx.conf /etc/nginx/nginx.conf
            aws s3 cp s3://${NginxConfigBucket}/demo-server.crt /etc/pki/tls/certs/demo-server.crt
            aws s3 cp s3://${NginxConfigBucket}/demo-server.key /etc/pki/tls/certs/demo-server.key
            chmod 400 /etc/pki/tls/certs/demo-server.*

            service nginx start

#########################################################################
# Auto Scaling Group

  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: LaunchConfiguration
    Properties:
      DesiredCapacity: !Ref DesiredInstanceAmount
      HealthCheckGracePeriod: !Ref HealthChkGracePeriod
      LaunchConfigurationName: !Ref LaunchConfiguration
      MaxSize: !Ref ASGMaxSize
      MinSize: !Ref ASGMinSize
      Cooldown: !Ref ASGCooldown
      HealthCheckType: EC2
      Tags:
        - Key: 'Name'
          Value: 'Redirector ASG'

        - Key: 'Project'
          Value: 'Cloud Migration'
          PropagateAtLaunch: true
      TerminationPolicies:
        - !Ref ASGTerminationPolicies
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub "${VPCStackName}-Subnet${AvailabilityZone}Id"
      TargetGroupARNs:
        - Fn::ImportValue: !Sub "${NLBStackName}-Redirector-Targets"
        - Fn::ImportValue: !Sub "${NLBStackName}-Redirector-Targets-SSL"

    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: !Ref UpdatePolicyMaxBatchSize
        MinInstancesInService: !Ref UpdatePolicyMinInstancesInService


###############################################################################
