AWSTemplateFormatVersion: '2010-09-09'

Description: 'ASG Template: EC2 Role, Auto Scaling Group & Launch Configuration'

Mappings:

  # AcctMap - use this if you wish to easily deploy this stack in
  # multiple accounts. e.g. PRODUCTION & DEVELOPMENT
  # If using with one account only, specify and reference only one
  # account, the other will be ignored.
  AcctMap:
    "452644920012" : # customize to your account
      "AcctName" : "DEVELOPMENT"
    "231435876663" : # customize to your account
      "AcctName" : "PRODUCTION"

  # AMIMap - use this to map AMIs in multiple regions and accounts
  # Only the region is required for public AMIs. Useful if you have
  # unshared private AMIs in multiple accounts & regions.
  AMIMap:
    us-west-2:
      "DEVELOPMENT" : "ami-e689729e"
      "PRODUCTION" : "ami-e689729e"
    us-east-1:
      "DEVELOPMENT" : "ami-8c1be5f6"
      "PRODUCTION" : "ami-8c1be5f6"
    us-east-2:
      "DEVELOPMENT" : "ami-c5062ba0"
      "PRODUCTION" : "ami-c5062ba0"

  KeypairMap:
    us-west-2:
      "DEVELOPMENT" : "oregon-dev"
      "PRODUCTION" : "oregon-prod"
    us-east-1:
      "DEVELOPMENT" : "virginia-dev"
      "PRODUCTION" : "oregon-prod"
    us-east-2:
      "DEVELOPMENT" : "demo-ec2-keypair"
      "PRODUCTION" : "demo-ec2-keypair"

  InstanceSizeMap:
    t2:
      "micro" : "t2.micro"
      "small" : "t2.small"
      "medium" : "t2.medium"
      "large" : "t2.large"
    m4:
      "small" : "m4.large"
      "medium" : "m4.xlarge"
      "large" : "m4.4xlarge"

Parameters:
  VPCStackName:
    Description: Name of the VPC stack we're referencing
    Type: String
    Default: demo-vpc

  NLBStackName:
    Description: Name of the NLB stack we're referencing
    Type: String
    Default: demo-nlb

  IAMStackName:
    Description: Name of the IAM stack we're referencing
    Type: String
    Default: demo-iam

  KeypairName:
    Description: The name of the keypair for SSH access to your EC2 instances
    Type: String
    Default: "demo-ec2-keypair"
    MinLength: "1"
    MaxLength: "30"

  Monitoring:
    Description: Toggle detailed instance monitoring for instances in the ASG.  Set to True for detailed monitoring. Additional fees will apply.
    Type: String
    MinLength: '1'
    MaxLength: '128'
    Default: false

  InstanceType:
    Description: Specifies the instance type of the EC2 instances that will be deployed into the ASG.
    Type: String
    AllowedValues: 
      - t2.micro
      - t2.medium
      - t2.large
      - m4.large
    Default: t2.micro

  DesiredInstanceAmount:
    Description: Desired number of instances in the ASG.
    Type: Number
    Default: 3

  HealthChkGracePeriod:
    Description: The length of time in seconds after a new EC2 instance comes into service that Auto Scaling starts checking its health.
    Type: Number
    Default: 300

  ASGMaxSize:
    Description: Maximum number of instances to be deployed into the ASG.
    Type: Number
    Default: 6

  ASGMinSize:
    Description: Minimum number of instances to be deployed into the ASG.
    Type: Number
    Default: 2

  ASGCooldown:
    Description: The number of seconds after a scaling activity is completed before any further scaling activities can start.
    Type: Number
    Default: 300

  ASGTerminationPolicies:
    Description: Used to specify the rules that dictate which instances are terminated during scale-in events.
    Type: String
    MinLength: '1'
    MaxLength: '128'
    Default: Default

  UpdatePolicyMaxBatchSize:
    Description: Specifies the maximum number of instances that AWS CloudFormation updates at a time.
    Type: Number
    Default: 1

  UpdatePolicyMinInstancesInService:
    Description: Minimum number of instances in service while other instances are being updated.
    Type: Number
    Default: 2

  PublicIP:
    Description: Set to True if you wish the instances in the ASG to have a public IP.
    Type: String
    Default: true
    AllowedValues: 
      - true
      - false

  NginxConfigBucket:
    Type: String
    Default: YourBucketName/Prefix

Resources:
#########################################################################
# IAM Role for EC2 instances to access S3 objects
  # ProdEC2S3Role:
  #   Type: "AWS::IAM::Role"
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         -
  #           Effect: "Allow"
  #           Principal:
  #             Service:
  #               - "ec2.amazonaws.com"
  #           Action:
  #             - "sts:AssumeRole"
  #     Path: "/"
  #     ManagedPolicyArns:
  #       - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess


#########################################################################
# Auto Scaling Group Launch Configuration

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: !Ref PublicIP
      ImageId: !FindInMap [AMIMap, !Ref "AWS::Region", !FindInMap [AcctMap, !Ref "AWS::AccountId", AcctName ] ]
      InstanceMonitoring: !Ref Monitoring
      InstanceType: !Ref InstanceType
      KeyName: !FindInMap [KeypairMap, !Ref "AWS::Region", !FindInMap [AcctMap, !Ref "AWS::AccountId", AcctName ] ]
      IamInstanceProfile: 
        Fn::ImportValue: !Sub "${IAMStackName}-EC2S3Profile"
      SecurityGroups:
        - Fn::ImportValue: !Sub "${VPCStackName}-SGEC2"
        - Fn::ImportValue: !Sub "${VPCStackName}-SGSSH"
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            yum update -y
            yum install -y nginx
            chkconfig nginx on

            aws s3 cp s3://${NginxConfigBucket}/nginx.conf /etc/nginx/nginx.conf
            aws s3 cp s3://${NginxConfigBucket}/demo-server.crt /etc/pki/tls/certs/demo-server.crt
            aws s3 cp s3://${NginxConfigBucket}/demo-server.key /etc/pki/tls/certs/demo-server.key
            chmod 400 /etc/pki/tls/certs/demo-server.*

            service nginx start

#########################################################################
# Auto Scaling Group

  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: LaunchConfiguration
    Properties:
      DesiredCapacity: !Ref DesiredInstanceAmount
      HealthCheckGracePeriod: !Ref HealthChkGracePeriod
      LaunchConfigurationName: !Ref LaunchConfiguration
      MaxSize: !Ref ASGMaxSize
      MinSize: !Ref ASGMinSize
      Cooldown: !Ref ASGCooldown
      HealthCheckType: EC2
      Tags:
        - Key: 'Name'
          Value: 'Demo ASG'
          PropagateAtLaunch: true
        - Key: 'Project'
          Value: 'Demo CloudFormation Project'
          PropagateAtLaunch: true
      TerminationPolicies:
        - !Ref ASGTerminationPolicies
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub "${VPCStackName}-SubnetAZ1Id"
        - Fn::ImportValue: !Sub "${VPCStackName}-SubnetAZ2Id"
        - Fn::ImportValue: !Sub "${VPCStackName}-SubnetAZ3Id"
      TargetGroupARNs:
        - Fn::ImportValue: !Sub "${NLBStackName}-Public-Targets"
        - Fn::ImportValue: !Sub "${NLBStackName}-Public-Targets-SSL"

    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: !Ref UpdatePolicyMaxBatchSize
        MinInstancesInService: !Ref UpdatePolicyMinInstancesInService


###############################################################################
# Outputs:
#   EC2Role:
#     Value: !Ref ProdEC2S3Role
#     Description: Role for EC2 instances to access S3
#     Export:
#       Name: !Sub "${AWS::StackName}-EC2Role"
